spring:
  application:
    name: domain

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      format_sql: false
      ddl_auto: create
    datasource:
      url: jdbc:mysql://localhost:3306/
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
