name: Dev to EC2

on:
  workflow_dispatch:  # ❗ 수동 실행만 허용

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Dev to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
cd ~/PICKCAR_BE_ACTION
sudo git pull origin main
cat > .env <<EOL
MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
DEV_DB_NAME=${{ secrets.DEV_DB_NAME }}
DEV_DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
EOL
sudo docker-compose down
sudo docker-compose up -d --build
EOF
